#!/bin/sh

sleep 3

echo "Network"

udhcpc -s /etc/udhcp/simple.script
echo ""
echo "loopback interface"
ifconfig lo 127.0.0.1
route add -host 127.0.0.1 lo


httpd -h /www/ &

exec /usr/bin/helloWorld

